# Generated by Django 4.1 on 2022-09-02 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('otc', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('win', 'Winter'), ('sum', 'Summer'), ('out', 'Outhemn'), ('spr', 'Spring')], default='win', max_length=5)),
                ('level', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PND', 'Pending'), ('ACPT', 'Accepted'), ('RJCT', 'Rejected')], default='NEW', max_length=4)),
                ('beauty_title', models.CharField(max_length=5)),
                ('title', models.CharField(blank=True, max_length=30, unique=True)),
                ('other_titles', models.CharField(blank=True, max_length=30)),
                ('connect', models.CharField(blank=True, max_length=50)),
                ('add_time', models.DateField(auto_now_add=True)),
                ('lofitude', models.FloatField(blank=True)),
                ('logitude', models.FloatField(blank=True)),
                ('height', models.FloatField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peaks.author')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peaks.author')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peaks.pereval')),
            ],
        ),
    ]
