# Generated by Django 4.1 on 2022-09-05 06:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peaks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='author',
        ),
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
        migrations.AddField(
            model_name='images',
            name='img',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='pereval',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='peaks.pereval'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='season',
            field=models.CharField(choices=[('win', 'Winter'), ('sum', 'Summer'), ('out', 'Outhemn'), ('spr', 'Spring')], max_length=5),
        ),
    ]
