# Generated by Django 4.1 on 2022-09-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaks', '0002_remove_images_author_remove_images_title_images_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(default=7, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pereval',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
